#!/usr/bin/env bun
// Build script for Google Apps Script

import * as esbuild from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "fs";

const command = process.argv[2] || "build";

if (command === "build") {
  console.log("🔨 Building for Apps Script (bundled from main classifier)...\n");
  
  // Bundle with esbuild
  console.log("1️⃣  Bundling with esbuild...");
  try {
    await esbuild.build({
      entryPoints: ["src/apps-script/wrapper.ts"],
      bundle: true,
      outfile: "build/bundled.js",
      format: "esm", // Use ES modules format
      target: "es2015",
      platform: "neutral",
    });
    console.log("✅ Bundled successfully\n");
  } catch (e) {
    console.error("❌ Bundling failed:", e);
    process.exit(1);
  }
  
  // Post-process: Convert to Apps Script compatible format
  console.log("2️⃣  Post-processing for Apps Script...");
  mkdirSync("build", { recursive: true });
  let js = readFileSync("build/bundled.js", "utf-8");
  
  // Remove export statements - functions will be top-level
  js = js.replace(/^export \{[^}]+\};?\s*$/gm, '');
  js = js.replace(/^export (function|const|var|let) /gm, '$1 ');
  
  const output = `// Auto-generated from TypeScript at: ${new Date().toISOString()}
// Source: src/apps-script/wrapper.ts + src/classifier.ts
// DO NOT EDIT THIS FILE DIRECTLY - Edit the TypeScript source instead
// This file is bundled from the main classifier to ensure consistency

${js}
`;
  
  writeFileSync("build/Code.gs", output);
  console.log("✅ Created build/Code.gs\n");
  
  console.log("🎉 Build complete!");
  console.log("\n📋 Next steps:");
  console.log("  1. Open https://script.google.com");
  console.log("  2. Create a new project (or open existing)");
  console.log("  3. Copy build/Code.gs");
  console.log("  4. Paste into the Code.gs file in Apps Script editor");
  console.log("  5. Save and run setupTriggers()");
} else {
  console.log("Usage: bun run gas [build]");
  console.log("\nCommands:");
  console.log("  build   - Bundle TypeScript to .gs file (default)");
}
