#!/usr/bin/env bun
// Build script for Google Apps Script

import { execSync } from "child_process";

const command = process.argv[2] || "build";

if (command === "build") {
  console.log("🔨 Building for Apps Script (local .gs file)...\n");
  
  // Compile TypeScript
  console.log("1️⃣  Compiling TypeScript...");
  try {
    execSync("tsc -p tsconfig.apps-script.json", { stdio: "inherit" });
    console.log("✅ TypeScript compiled\n");
  } catch (e) {
    console.error("❌ TypeScript compilation failed");
    process.exit(1);
  }
  
  // Create .gs file
  console.log("2️⃣  Creating .gs file...");
  const { mkdirSync, readFileSync, writeFileSync } = await import("fs");
  mkdirSync("build", { recursive: true });
  const js = readFileSync("build/compiled/Code.js", "utf-8");
  
  const header = `// Auto-generated from TypeScript at: ${new Date().toISOString()}
// Source: src/apps-script/Code.ts
// DO NOT EDIT THIS FILE DIRECTLY - Edit the TypeScript source instead

`;
  
  writeFileSync("build/Code.gs", header + js);
  console.log("✅ Created build/Code.gs\n");
  
  console.log("🎉 Build complete!");
  console.log("\n📋 Next steps:");
  console.log("  1. Open https://script.google.com");
  console.log("  2. Create a new project (or open existing)");
  console.log("  3. Copy build/Code.gs");
  console.log("  4. Paste into the Code.gs file in Apps Script editor");
  console.log("  5. Save and run setupTriggers()");
} else {
  console.log("Usage: bun run gas [build]");
  console.log("\nCommands:");
  console.log("  build   - Compile TypeScript to .gs file (default)");
}
